# Generated by Django 4.2.4 on 2023-12-08 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DaysOfTheWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_days",
                    models.CharField(
                        choices=[
                            ("M", "Monday"),
                            ("T", "Tuesday"),
                            ("W", "Wednesday"),
                            ("H", "Thursday"),
                            ("F", "Friday"),
                            ("S", "Saturday"),
                            ("U", "Sunday"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("working_days", models.ManyToManyField(to="reception.daysoftheweek")),
            ],
        ),
    ]
