# Generated by Django 4.2.4 on 2023-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="available_time_from",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="available_time_to",
            field=models.TimeField(null=True),
        ),
    ]
