# Generated by Django 4.2.4 on 2023-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0005_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="am_pm",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
