# Generated by Django 4.2.4 on 2023-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0006_appointment_am_pm"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="message",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
