# Generated by Django 4.2.4 on 2023-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0007_schedule_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="from_am_pm",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="to_am_pm",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
