# Generated by Django 4.2.4 on 2023-12-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0008_schedule_from_am_pm_schedule_to_am_pm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysoftheweek",
            name="available_days",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                max_length=9,
                null=True,
            ),
        ),
    ]
