# Generated by Django 4.2.4 on 2023-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0009_alter_daysoftheweek_available_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("A", "Active"), ("C", "Confirmed"), ("D", "Done")],
                max_length=1,
                null=True,
            ),
        ),
    ]
