# Generated by Django 4.2.4 on 2023-11-27 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="diseaseJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease_name", models.CharField(max_length=100)),
                ("month", models.IntegerField()),
                ("years", models.IntegerField()),
                ("duration", models.DurationField()),
                (
                    "status",
                    models.CharField(
                        choices=[("R", "Resolved"), ("NR", "Not Resolved")],
                        max_length=2,
                    ),
                ),
                ("journey_remark", models.TextField()),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
