# Generated by Django 4.2.4 on 2023-11-27 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0002_useraccount_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="user_id",
        ),
    ]
