# Generated by Django 4.2.4 on 2023-12-05 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0006_alter_useraccount_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="name",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="fname",
            field=models.CharField(default="Hello", max_length=255),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="lname",
            field=models.CharField(default="Singh", max_length=255),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="alternate_contact",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
