# Generated by Django 4.2.4 on 2023-12-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0007_remove_useraccount_name_useraccount_fname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="fname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="lname",
            field=models.CharField(max_length=255),
        ),
    ]
