# Generated by Django 4.2.4 on 2023-12-05 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0008_alter_useraccount_fname_alter_useraccount_lname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="fname",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="useraccount",
            old_name="lname",
            new_name="lastname",
        ),
    ]
