# Generated by Django 4.2.4 on 2023-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0009_rename_fname_useraccount_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="lastname",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
