# Generated by Django 4.2.4 on 2023-12-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0010_alter_useraccount_lastname"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="status",
            field=models.CharField(
                choices=[("A", "Available"), ("W", "Away"), ("O", "Occupied")],
                max_length=1,
                null=True,
            ),
        ),
    ]
