# Generated by Django 4.2.4 on 2023-12-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0011_useraccount_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="date_joined",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
