# Generated by Django 4.2.4 on 2023-12-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0012_useraccount_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="date_joined",
            field=models.DateField(null=True),
        ),
    ]
