# Generated by Django 4.2.4 on 2023-12-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0013_alter_useraccount_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("A", "Available"), ("W", "Away"), ("O", "Occupied")],
                max_length=1,
                null=True,
            ),
        ),
    ]
