# Generated by Django 4.2.4 on 2023-12-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0015_alter_useraccount_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="address",
            field=models.TextField(default="Hello"),
        ),
    ]
