# Generated by Django 4.2.4 on 2023-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_doc", "0018_useraccount_patient_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
